{
  "type": "record",
  "name": "rating_submitted",
  "version": 1.0,
  "namespace": "com.fandutech.events",
  "fields": [
    {
      "name": "order_id",
      "type": "string"
    },
    {
      "name": "customer_id",
      "type": "string"
    },
    {
      "name": "rating",
      "type": "int"
    },
    {
      "name": "comment",
      "type": [
        "null",
        "string"
      ],
      "default": null
    },
    {
      "name": "timestamp",
      "type": "string",
      "logicalType": "timestamp-millis"
    }
  ]
}